In [35]:
from __future__ import print_function
import torch
import numpy as np

In [3]:
# initialized with values in allocated memory
x = torch.empty(5,3)
print(x)

tensor([[3.0881e+29, 7.5589e+28, 5.2839e-11],
        [2.7604e+20, 1.1703e-19, 1.5637e-01],
        [1.2108e+25, 1.8611e+34, 5.0782e+31],
        [4.2964e+24, 1.7753e+28, 1.3458e-14],
        [1.4585e-19, 9.3233e-09, 1.1703e-19]])


In [5]:
# randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.1352, 0.5031, 0.1402],
        [0.7070, 0.2441, 0.1904],
        [0.6923, 0.4114, 0.0768],
        [0.3670, 0.2665, 0.8768],
        [0.1479, 0.8050, 0.3726]])


In [7]:
# matrix filled with zeros and of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# directly input the values fromd data
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
# create a tensor like the one we had before
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0843, -0.3467, -1.7458],
        [ 1.8860,  1.3111, -0.1636],
        [ 0.6215, -0.5554,  0.1342],
        [ 0.0311, -2.1001, -0.5548],
        [-1.0448, -1.1500, -0.6432]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
# multiple syntaxes for addition
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.9412,  0.0924, -0.7694],
        [ 2.1351,  1.4769,  0.8126],
        [ 1.6126,  0.3024,  0.5436],
        [ 0.8960, -1.6500, -0.0761],
        [-0.6795, -0.4731, -0.4243]])


In [14]:
print(torch.add(x,y))

tensor([[ 1.9412,  0.0924, -0.7694],
        [ 2.1351,  1.4769,  0.8126],
        [ 1.6126,  0.3024,  0.5436],
        [ 0.8960, -1.6500, -0.0761],
        [-0.6795, -0.4731, -0.4243]])


tensor([[ 1.0843, -0.3467, -1.7458],
        [ 1.8860,  1.3111, -0.1636],
        [ 0.6215, -0.5554,  0.1342],
        [ 0.0311, -2.1001, -0.5548],
        [-1.0448, -1.1500, -0.6432]])


In [24]:
# indexing
print(x)
print(x[:,1])
print(x[2,:])

tensor([[ 1.0843, -0.3467, -1.7458],
        [ 1.8860,  1.3111, -0.1636],
        [ 0.6215, -0.5554,  0.1342],
        [ 0.0311, -2.1001, -0.5548],
        [-1.0448, -1.1500, -0.6432]])
tensor([-0.3467,  1.3111, -0.5554, -2.1001, -1.1500])
tensor([ 0.6215, -0.5554,  0.1342])


In [34]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### converting a torch tensor to a numpy array

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [43]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [73]:
# see how the numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([30., 30., 30., 30., 30.])
[30. 30. 30. 30. 30.]


### converting NumPy Array into Torch Tensor

In [76]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
