# BASELINE MODEL

Using [this webpage](https://medium.com/@pallawi.ds/ai-starter-train-and-test-your-first-neural-network-classifier-in-keras-from-scratch-b6a5f3b3ebc4) to help me out

import statements

In [126]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import sklearn
import numpy as np
import random

# import keras
import keras
from keras.models import Sequential
from keras import backend as K
backend_keras = keras.backend.backend()
print("keras is using", backend_keras,"as the backend")
from keras.layers.core import Dense
from keras.optimizers import SGD

keras is using tensorflow as the backend


# Load the data

In [127]:
train_images = np.load("training_set.npy")
labels = np.load("training_redshift_labels.npy")
print(train.shape)
print(labels.shape)
train_images = list(train_images)
labels = list(labels)

(6171, 50, 50)
(6171,)


# Preprocessing

In [128]:
# Shuffle the data
new_train_images = []
new_labels = []
while train_images:
    i = random.randrange(len(train_images))
    new_train_images.append(train_images[i])
    del train_images[i]
    new_labels.append(labels[i])
    del labels[i]
train_images = np.array(new_train_images[:])
labels = np.array(new_labels)

In [129]:
print(train.shape)
print(labels.shape)

(6171, 50, 50)
(6171,)


### make the labels so that the model can learn them
Sofar the labels are floats 

In [130]:
# display the labels
l = []
for i in labels:
    if i not in l: l.append(i)
l.sort()
print(l,"\nThere are",len(l),"labels. So the the problem is an image classification into",len(l),"classes")

[5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5, 12.0, 12.5, 13.0] 
There are 17 labels. So the the problem is an image classification into 17 classes


In [131]:
# define the train labels in len 17 arrays

train_labels = []
for i in labels:
    arr = np.zeros(17)
    index = int(np.round((i-5)*2,0))
    arr[index]=1
    train_labels.append(arr[:])
    
train_labels = np.array(train_labels)
print("train_labels shape =", train_labels.shape,"\nFirst 3 entries:")
print(train_labels[:3])

train_labels shape = (6171, 17) 
First 3 entries:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


### normalise the images
because the values of the pixels in these images are somewhat unconventional I normalize by dividing by 70 instead of 255, this is because I checked and the max value was 66 point something.

In [132]:
# normalize images
train_images_n = train_images / 70.0 # n for normalized
print("max : ",np.max(train_images_n))
print("min : ",np.min(train_images_n))

max :  0.9500968
min :  0.0


Flatten the images for training

In [133]:
train_images_flatten = np.array([i.flatten("C") for i in train_images])
print("triain images flatten shape : ",train_images_flatten.shape)

triain images flatten shape :  (6171, 2500)


## Define Architecture
The input size is 2500 and the output is gonna have size 17. I'm gonna make it single hidden layer.

In [134]:
model = Sequential()

model.add(Dense(350, input_shape=(2500,), activation="sigmoid"))
model.add(Dense(17, activation="softmax"))

print("printing summary of model")
model.summary()

printing summary of model
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 350)               875350    
_________________________________________________________________
dense_6 (Dense)              (None, 17)                5967      
Total params: 881,317
Trainable params: 881,317
Non-trainable params: 0
_________________________________________________________________


## Compile the mode
You can compile a network (model) as many times as you want. You need to compile the model if you wish to change the loss function, optimizer or matrices.

You need a compiled model to train (because training uses the loss function and the optimizer). But it’s not necessary to compile the model when testing the model on a new data.

In [146]:
# Initialize the initial learning rate and number of Epochs
INIT_LR = 0.01
EPOCHS = 25

# compile the model using SGD optimizer (see imports) and categorical cross-entropy loss
print("[INFO] Compiled the network...")
opt = SGD(lr = INIT_LR) # stochastic gradient descent
model.compile(loss="categorical_crossentropy", optimizer=opt,
             metrics=["accuracy"])

[INFO] Compiled the network...


In [147]:
# split the train into a train and valid set
ratio = 0.8
cut = int(ratio*len(train_images_flatten))
trainX = train_images_flatten[:cut]
trainY = train_labels[:cut]
valX = train_images_flatten[cut:]
valY = train_labels[cut:]

## OR possible import an old network / pre-defined network for (re)training

# Train the neural network

In [ ]:
H = model.fit(trainX, trainY,
             validation_data=(valX,valY),
             epochs=EPOCHS, batch_size=32)

Train on 4936 samples, validate on 1235 samples
Epoch 1/25
4936/4936 [==============================] - 1s 237us/step - loss: 2.5542 - accuracy: 0.1584 - val_loss: 2.4445 - val_accuracy: 0.2138
Epoch 2/25
2080/4936 [===========>..................] - ETA: 0s - loss: 2.3711 - accuracy: 0.2245

# OR Import a neural network

# Make a prediction